- name: Ansible Jenkins Playbook
  remote_user: godi
  become: yes
  hosts: TEST
  tasks:
    - name: Install Java
      command: apt install -y default-jre
    - name: Download Artifact
      get_url:
        url: http://34.125.73.14:8081/service/rest/v1/search/assets/download?sort=version&direction=desc&maven.groupId=com.mycompany.app&maven.artifactId=my-app&maven.extension=jar
        dest: /opt/my-app.jar
